import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { APP_TITLE, LAYOUT } from './constants';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen h-full m-0`}
      >
        <header
          className=" text-white p-6"
          style={{ height: LAYOUT.HEADER_HEIGHT }}
        >
          <h1 className="text-3xl font-extrabold text-center">{APP_TITLE}</h1>
        </header>
        <main className="flex flex-1 min-h-0 py-5">{children}</main>
      </body>
    </html>
  );
}
